require(devtools)
install_version("kernlab", version="0.9-24")
install_version("ROCR", version="1.0-7")
install_version("class", version="7.3-14")
install_version("mvtnorm", version="1.0-8")
install_version("multcomp", version="1.4-8")
install_version("coin", version="1.2-2")
install_version("party", version="1.0-25")
install_version("e1071", version="1.6-7")
install_version("randomForest", version="4.6-12")
